### PR TITLE
bug: fixed issue to be able to remove the tmp folder when it has content

### PR DESCRIPTION
**Pull request by xiCO2k**

### CODE REVIEW

**Comment by xiCO2k** [comment]
Hey @jprichardson Can you check my pull request?

**Comment by xiCO2k** [comment]
Hey @jprichardson can you check my pull request?

**Comment by xiCO2k** [comment]
hey @jprichardson any luck checking my pull request?

**Comment by jprichardson** [comment]
`fs.remove` should do this - it's from `fs-extra`. 

I have no intention of maintaining this package anymore.

**Comment by xiCO2k** [comment]
got it, maybe just update the fs-extra package should fix it, still use it on one of my packages.

**Comment by xiCO2k** [comment]
Added a new commit, let me know if is possible for you to add a new version to NPM, thanks.

**Pull request closed without merging**
